version: "3.0"
services:
  db:
    container_name: "fastapi_education"
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_education
    ports:
      - "5436:5432"
    networks:
      - custom


networks:
  custom:
    driver: bridge